POST http://localhost:8080/api/ticket
Content-Type: application/json

{
  "train": 6446,
  "seat": 1,
  "from": 2524,
  "to": 2263,
  "passenger": 4
}

###

DELETE http://localhost:8080/api/ticket/2

###

GET http://localhost:8080/api/ticket/2

###

GET http://localhost:8080/api/tickets/active

