### login
POST http://localhost:8080/api/session
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### get session
GET http://localhost:8080/api/session
Accept: application/json

### get user

GET http://localhost:8080/api/user/admin
Accept: application/json

###

GET http://localhost:8080/api/user/user
Accept: application/json

### log out

DELETE http://localhost:8080/api/session

